#!/bin/bash
# Script to start ngrok tunnels for backend and frontend

echo "======================================================================"
echo "🚀 Starting ngrok tunnels"
echo "======================================================================"
echo ""

# Check if ngrok is configured
if ! ~/ngrok config check &> /dev/null; then
    echo "⚠️  ngrok is not configured yet!"
    echo ""
    echo "Please follow these steps:"
    echo "1. Sign up at: https://dashboard.ngrok.com/signup"
    echo "2. Get your authtoken from: https://dashboard.ngrok.com/get-started/your-authtoken"
    echo "3. Run: ~/ngrok config add-authtoken YOUR_TOKEN"
    echo ""
    exit 1
fi

echo "Starting tunnels..."
echo ""
echo "📡 Backend API tunnel (port 8001):"
echo "   Run in a new terminal: ~/ngrok http 8001"
echo ""
echo "🌐 Frontend tunnel (port 3000):"
echo "   Run in another terminal: ~/ngrok http 3000"
echo ""
echo "======================================================================"
echo "💡 Quick Start Guide"
echo "======================================================================"
echo ""
echo "1. Make sure your servers are running:"
echo "   - Backend: python3 src/api.py (port 8001)"
echo "   - Frontend: npm run dev (port 3000)"
echo ""
echo "2. Open TWO new terminal windows and run:"
echo "   Terminal 1: ~/ngrok http 8001"
echo "   Terminal 2: ~/ngrok http 3000"
echo ""
echo "3. Copy the ngrok URLs (they look like: https://abc123.ngrok.io)"
echo ""
echo "4. Update .env.local with the backend ngrok URL:"
echo "   NEXT_PUBLIC_API_URL=https://YOUR_BACKEND_NGROK_URL"
echo ""
echo "5. Restart your frontend (npm run dev)"
echo ""
echo "6. Share the FRONTEND ngrok URL with others!"
echo ""
echo "======================================================================"
